proto_outdir = "./.vendor"
[[dependencies]]
  target = "github.com/envoyproxy/protoc-gen-validate"
  branch = "master"
  ignores = ["./java", "./tests"]

[[dependencies]]
  target = "github.com/googleapis/api-common-protos"
  branch = "master"
