logging:
  version: 1
  disable_existing_loggers: true
  handlers:
    default:
      level: INFO
      formatter: standard
      class: logging.StreamHandler
      stream: ext://sys.stdout
  formatters:
    standard:
      format: "[%(asctime)s] [%(levelname)s] %(message)s"
      datefmt: "%H:%M:%S"
  loggers:
    "":
      level: INFO
      handlers:
        - default

database:
  connection_string: ${kube:do-db-credentials/connection-string}
  name: main

server:
  host_and_port: 0.0.0.0:8080

blob_storage:
  connection_string: ${kube:blob-storage/connection-string}
  container: "scraped-data"

single_scraper:
  url: https://delphai-source-scraper.azurewebsites.net/api/scrape-single-url

english_ner:
  uri: https://azure-ml.delphai.red/api/v1/service/ner-tagger/score
  key: 1r4amNny4qvglU3pvJQYMbizsE0hjQx2

german_ner:
  uri: https://azure-ml.delphai.red/api/v1/service/ger-ner/score
  key: AhCgR7uzrXGCMKi9oVbd9kxC6RYVfk6J

nel:
  url: https://api.delphai.red/names-matcher/delphai.namesmatcher.NamesMatcher.match
  address: names-matcher-grpc.names-matcher:80

language_detector:
  url: https://api.delphai.blue/translation/delphai.Translation.detect_language

translator:
  url: https://api.delphai.blue/translation/delphai.Translation.translate
  address: translation-grpc.translation:80
