database:
  connection_string: ${env:DB_CONNECTION}

blob_storage:
  connection_string: ${env:AZURE_BLOB}
  container: "scraped-data"

names-matcher:
  address: names-matcher.grpc.delphai.red:80

translation:
  address: translation.grpc.delphai.red:80